### ISSUE TITLE
ANI Open 找不到希望關聯的目標

### ISSUE THREAD

**Issue by swalok47716** [AnimacX/AnimacX#16]
ANI Open的查詢列表中找不到希望關聯的動畫，輸入全名也不行

**Comment by saddit** [comment]
只有一部分动画是可以关联上的，没有的资源无法关联

**Comment by swalok47716** [comment]
謝謝回覆，但好像不完全是那樣
例如在當季中 "DDDD 惡魔的破壞" 在列表中查詢不到 卻可以在 "敗北女角太多了！"查詢到

**Comment by saddit** [comment]
DDD这个比较特殊，它是提前放送了三集，以至于不同的来源将它视为不同季度的新番，这个暂时不太好解决，也许后续会有优化的算法

**Comment by swalok47716** [comment]
了解
