### ISSUE TITLE
【问题】两位数剧集排序错误

### ISSUE THREAD

**Issue by YunfangHou** [AnimacX/AnimacX#17]
如图，第 10、11 集反而会排在第 2 集前面。

不过只有资源关联成功才会出现这个问题；关联不到资源的话，排序就是正常的。

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/842e552d-6f0f-4ff5-9f8b-e171b27c7fb4">

**Comment by saddit** [comment]
将会在下一个版本中修复
