### ISSUE TITLE
【问题】彈幕來源重複

### ISSUE THREAD

**Issue by swalok47716** [AnimacX/AnimacX#23]
經常在播放中看到重複的彈幕，但刪除彈幕來源並不一定能解決問題
![CleanShot 2024-09-26 at 11 17 17](https://github.com/user-attachments/assets/a7cb3d96-4c95-4ac4-a4c9-f2621c5b537f)

**Comment by saddit** [comment]
这种情况一般是两个弹幕来源的弹幕是相同的，删掉其中一个可以解决。

提供一下使用的版本号，确认是否为最新版本

**Comment by swalok47716** [comment]
0.3.0

**Comment by Li-lac** [comment]
为什么我这里没有删除的按键，也是0.3.0
<img width="564" alt="image" src="https://github.com/user-attachments/assets/72acd846-ddfe-4074-926b-82d10b421ef2">

**Comment by saddit** [comment]
> 为什么我这里没有删除的按键，也是0.3.0
> 
> <img width="564" alt="image" src="https://github.com/user-attachments/assets/72acd846-ddfe-4074-926b-82d10b421ef2">
> 
> 

之前版本是可以在设置中打开按钮显示，后面移除了，保留左滑删除的行为

**Comment by saddit** [comment]
> 为什么我这里没有删除的按键，也是0.3.0
> 
> <img width="564" alt="image" src="https://github.com/user-attachments/assets/72acd846-ddfe-4074-926b-82d10b421ef2">
> 
> 

之前版本是可以在设置中打开按钮显示，后面移除了，保留左滑删除的行为

**Comment by saddit** [comment]
@swalok47716 我想知道为什么你的主题色是蓝色

**Comment by swalok47716** [comment]
![CleanShot 2024-10-02 at 16 43 43](https://github.com/user-attachments/assets/6dc5db1b-026f-4835-9b50-4e6a7911504f)
外觀設定的 Accent color 可以調

**Comment by saddit** [comment]
由于未提供测试用例，未能复现出次异常，issue暂时关闭，欢迎复现时重新开放讨论。
